# CMake generated Testfile for 
# Source directory: E:/vs17project/libxml2/libxml2-2.12.3
# Build directory: E:/vs17project/libxml2/libxml2-2.12.3/win-build
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(runtest "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/runtest.exe" "--out" "E:/vs17project/libxml2/libxml2-2.12.3/win-build")
  set_tests_properties(runtest PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;538;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(runtest "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/runtest.exe" "--out" "E:/vs17project/libxml2/libxml2-2.12.3/win-build")
  set_tests_properties(runtest PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;538;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(runtest "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/runtest.exe" "--out" "E:/vs17project/libxml2/libxml2-2.12.3/win-build")
  set_tests_properties(runtest PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;538;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(runtest "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/runtest.exe" "--out" "E:/vs17project/libxml2/libxml2-2.12.3/win-build")
  set_tests_properties(runtest PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;538;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(runtest NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(runsuite "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/runsuite.exe")
  set_tests_properties(runsuite PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;539;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(runsuite "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/runsuite.exe")
  set_tests_properties(runsuite PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;539;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(runsuite "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/runsuite.exe")
  set_tests_properties(runsuite PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;539;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(runsuite "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/runsuite.exe")
  set_tests_properties(runsuite PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;539;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(runsuite NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testchar "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/testchar.exe")
  set_tests_properties(testchar PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;546;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testchar "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/testchar.exe")
  set_tests_properties(testchar PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;546;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testchar "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/testchar.exe")
  set_tests_properties(testchar PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;546;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testchar "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/testchar.exe")
  set_tests_properties(testchar PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;546;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(testchar NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testdict "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/testdict.exe")
  set_tests_properties(testdict PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;547;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testdict "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/testdict.exe")
  set_tests_properties(testdict PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;547;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testdict "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/testdict.exe")
  set_tests_properties(testdict PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;547;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testdict "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/testdict.exe")
  set_tests_properties(testdict PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;547;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(testdict NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testparser "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/testparser.exe")
  set_tests_properties(testparser PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;548;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testparser "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/testparser.exe")
  set_tests_properties(testparser PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;548;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testparser "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/testparser.exe")
  set_tests_properties(testparser PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;548;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testparser "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/testparser.exe")
  set_tests_properties(testparser PROPERTIES  _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;548;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(testparser NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testrecurse "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/testrecurse.exe")
  set_tests_properties(testrecurse PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;549;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testrecurse "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/testrecurse.exe")
  set_tests_properties(testrecurse PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;549;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testrecurse "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/testrecurse.exe")
  set_tests_properties(testrecurse PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;549;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testrecurse "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/testrecurse.exe")
  set_tests_properties(testrecurse PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;549;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(testrecurse NOT_AVAILABLE)
endif()
if(CTEST_CONFIGURATION_TYPE MATCHES "^([Dd][Ee][Bb][Uu][Gg])$")
  add_test(testThreads "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Debug/testThreads.exe")
  set_tests_properties(testThreads PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;550;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ee][Aa][Ss][Ee])$")
  add_test(testThreads "E:/vs17project/libxml2/libxml2-2.12.3/win-build/Release/testThreads.exe")
  set_tests_properties(testThreads PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;550;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Mm][Ii][Nn][Ss][Ii][Zz][Ee][Rr][Ee][Ll])$")
  add_test(testThreads "E:/vs17project/libxml2/libxml2-2.12.3/win-build/MinSizeRel/testThreads.exe")
  set_tests_properties(testThreads PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;550;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
elseif(CTEST_CONFIGURATION_TYPE MATCHES "^([Rr][Ee][Ll][Ww][Ii][Tt][Hh][Dd][Ee][Bb][Ii][Nn][Ff][Oo])$")
  add_test(testThreads "E:/vs17project/libxml2/libxml2-2.12.3/win-build/RelWithDebInfo/testThreads.exe")
  set_tests_properties(testThreads PROPERTIES  WORKING_DIRECTORY "E:/vs17project/libxml2/libxml2-2.12.3" _BACKTRACE_TRIPLES "E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;550;add_test;E:/vs17project/libxml2/libxml2-2.12.3/CMakeLists.txt;0;")
else()
  add_test(testThreads NOT_AVAILABLE)
endif()
